# Generated by Django 4.0.4 on 2022-06-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagblog'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='visible',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
